// src/routes/login/+page.svelte
<script lang="ts">
	import { authStore } from '$stores/authStore';
	import { get } from 'svelte/store';

	let username = '';
	let password = '';
	let { error } = get(authStore);
</script>

<div class="flex min-h-full flex-col justify-center px-6 py-12 lg:px-8">
	<div class="sm:mx-auto sm:w-full sm:max-w-sm">
		<h2 class="mt-10 text-center text-2xl/9 font-bold tracking-tight text-gray-900">
			Sign in to your account
		</h2>
	</div>
	{#if error}
		<div class="sm:mx-auto sm:w-full sm:max-w-sm">
			<p class="error">{error}</p>
		</div>
	{/if}

	<form method="POST" action="?/login">
		<div class="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
			<div class="space-y-6">
				<div>
					<label for="text" class="block text-sm/6 font-medium text-gray-900">Username</label>
					<div class="mt-2">
						<input
							type="text"
							name="username"
							id="username"
							autocomplete="username"
							required
							class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
							bind:value={username}
						/>
					</div>
				</div>

				<div>
					<div class="flex items-center justify-between">
						<label for="password" class="block text-sm/6 font-medium text-gray-900">Password</label>
					</div>
					<div class="mt-2">
						<input
							type="password"
							name="password"
							id="password"
							autocomplete="current-password"
							required
							class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6"
							bind:value={password}
						/>
					</div>
				</div>

				<div>
					<button
						type="submit"
						class="flex w-full justify-center rounded-md bg-indigo-600 px-3 py-1.5 text-sm/6 font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
						>Sign in</button
					>
				</div>
			</div>
		</div>
	</form>
</div>

<style>
	.error {
		color: red;
	}
</style>

// src/app/login/page.tsx
import { loginAction } from '@/lib/actions/auth';

export default function LoginPage() {
	return (
		<div className="flex min-h-screen items-center justify-center bg-gray-900 px-4">
			<div className="w-full max-w-md space-y-8 rounded-lg bg-gray-800 p-8 shadow-lg">
				<div className="text-center">
					<h1 className="text-3xl font-bold text-white">ACC Server Manager</h1>
					<p className="mt-2 text-gray-400">Sign in to manage your servers</p>
				</div>

				<form action={loginAction} className="space-y-6">
					<div>
						<label htmlFor="username" className="mb-2 block text-sm font-medium text-gray-300">
							Username
						</label>
						<input
							id="username"
							name="username"
							type="text"
							autoComplete="username"
							required
							className="form-input w-full"
						/>
					</div>

					<div>
						<label htmlFor="password" className="mb-2 block text-sm font-medium text-gray-300">
							Password
						</label>
						<input
							id="password"
							name="password"
							type="password"
							autoComplete="current-password"
							required
							className="form-input w-full"
						/>
					</div>

					<button
						type="submit"
						className="w-full rounded-md bg-blue-600 px-4 py-3 font-medium text-white transition-colors hover:bg-blue-700 focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-800 focus:outline-none"
					>
						Sign in
					</button>
				</form>
			</div>
		</div>
	);
}
